[build]
functions = "func"
command = "npm install && npm run build && node zipFunctions.js"
publish = "build"

[dev]
functions="./src/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

#This rule allows users to directly go to urls in react (ex: going to www.websiteurl.com/login loads login page instead of a 404)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200