[build]
functions = "./src/functions"
command = "npm run build"
publish = "build"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[redirects]]
from = "/*"
to = "/.netlify/functions/:splat"
status = 200
